### ISSUE TITLE
远程登录wisnucoffice，设备信息显示的是局域网内的设备

### ISSUE THREAD

**Issue by Leoan0131** [wisnuc/wisnuc-desktop-windows#106]
![default](https://user-images.githubusercontent.com/24586770/34056634-c67e9a5a-e20e-11e7-82b6-06ed894df259.png)

**Comment by juncaixinchi** [comment]
这个是因为修改菜单栏造成的Bug，因为station还没有提供设备信息的远程API，所以云连接时，前端目前会隐藏`设备信息`一栏
