### ISSUE TITLE
task任务显示bug？

### ISSUE THREAD

**Issue by Leoan0131** [wisnuc/wisnuc-desktop-windows#107]
![image](https://user-images.githubusercontent.com/24586770/34066942-745192ce-e253-11e7-9044-0c0586c318b5.png)
已经move完毕，但任务中还在继续

**Comment by juncaixinchi** [comment]
可能是文件夹内部有文件没有移动完毕，或者出错了，这个需要进一步确定

**Comment by juncaixinchi** [comment]
更新了UI
