### ISSUE TITLE
下载任务时，右键单击“我的文件”内文件，弹出文件操作弹框，不进行下一步操作；待下载任务传输成功时，弹框出现变更

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/wisnuc-desktop-windows#131]
![qq 20171229144723](https://user-images.githubusercontent.com/22342734/34431269-ad3927c8-eca8-11e7-861e-798369a19259.png)

**Comment by juncaixinchi** [comment]
这是因为当前文件夹有文件更新，会自动刷新页面，使被选择的项目丢失。

现修改为 当右键菜单打开时不刷新页面，当两个及以上项目被选择时，也不刷新页面
