### ISSUE TITLE
传输文件关闭网络并暂停，再次连接网络后未进行下载

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/wisnuc-desktop-windows#14]
测试步骤：
1.登录wisnuc                                                             
2.关闭网络                                                       
3.选择文件进行下载 
4.连接网络查看

实际结果：
文件联网后恢复下载后未下载

期待结果：
文件联网后恢复下载

**Comment by Leoan0131** [comment]
根据测试步骤，最新版本在关闭网络情况下是无法添加到传输列表的。请再次测试。
