### ISSUE TITLE
下载传输中，立即上传正在下载的文件夹，出现错误

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/wisnuc-desktop-windows#18]
测试步骤：
1.登录wisnuc
2.选择文件夹下载                                                                  
3.下载传输中，立即上传正在下载的文件夹

测试结果：
下载过程中，拖动本地文件到传输列表界面，三四次后客户端显示一片空白

**Comment by kangxuwinsun** [comment]
待确定

**Comment by Leoan0131** [comment]
阻断用户上传正在被下载的目录

**Comment by juncaixinchi** [comment]
目前一般会报`文件不可读`的错误
