### ISSUE TITLE
重命名正在上传的文件，上传失败

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/wisnuc-desktop-windows#19]
测试步骤：
1.登录wisnuc                                                             
2.选择文件上传                                                             
3.传输途中 正在上传的文件更改拓展名称

当前结果：
重命名后的文件上传失败，传输列表在上传结束后还一直显示失败，无法结束

**Comment by Leoan0131** [comment]
@juncaixinchi ，上传任务应该继续，而重命名需要失败，并提示用户，该文件正在上传中不能重命名。

**Comment by juncaixinchi** [comment]
fixed 重命名后报`文件不可读`的错误
