### ISSUE TITLE
删除本地正在下载的文件夹，传输依旧继续，但本地无文件夹显示

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/wisnuc-desktop-windows#20]
测试步骤：
登录wisnuc
下载文件夹传输
删除本地的文件夹，查看目录

测试结果：
继续进行下载传输并完成，但本地已不显示文件夹。

**Comment by juncaixinchi** [comment]
fixed 删除本地正在下载的文件夹后 会报文件不可读的错误
