### ISSUE TITLE
删除“我的文件”页jpg格式图片，“我的照片”依旧显示已删除的图片

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/wisnuc-desktop-windows#22]
测试步骤：
登录wisnuc上传照片至我的文件页
进入我的照片页查看
删除上传的照片，再次查看我的照片页

当前结果：
我的照片页依旧显示已删除照片。

**Comment by Leoan0131** [comment]
https://github.com/wisnuc/appifi/issues/388

**Comment by Leoan0131** [comment]
merged with #37
