### ISSUE TITLE
创建共享文件夹，不给于管理员权限，管理员无法看到此共享文件夹

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/wisnuc-desktop-windows#24]
当创建共享文件夹时，不给于管理员读写权限，管理员无法看到此共享文件夹
是否更改定义。

**Comment by Leoan0131** [comment]
需更改定义，待设计明确。

**Comment by Leoan0131** [comment]
@juncaixinchi 在设置界面，管理员可以看到建立的全部共享文件夹，不论管理员账户是否有权限进入这个文件夹。
