### ISSUE TITLE
文件/文件夹的移动无效

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/wisnuc-desktop-windows#31]
对文件进行删除，提示 bad request。

**Comment by Leoan0131** [comment]
应该开4个issue。由于文件/文件夹的Move API未提供，提交issue至appifi。
其他三个已经修复，后续测试如仍有问题，再开。先将本issue改为移动功能无效。

**Comment by Leoan0131** [comment]
API未提供，功能交付后涵盖在未来的用户测试中再进行测试。
