### ISSUE TITLE
共享盘页面切换较为繁琐

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/wisnuc-desktop-windows#34]
共享盘的几个页面切换混乱，新建共享盘必须在菜单栏下的系统设置里面新建才可以
创建完共享盘，直接点击进入共享盘，会再一次跳转到菜单页下的共享盘页，再次点击才能进入共享盘。

**Comment by Leoan0131** [comment]
与普通用户是否能创建共享盘、共享盘的权限设置debug等敲定后，再设计这块UX

**Comment by juncaixinchi** [comment]
v1.2.15版已作优化
* 在共享盘中无共享盘时，可以跳转至系统设置的共享盘管理页面进行添加
* 在共享盘内点击可直接进入相应共享盘内
