### ISSUE TITLE
不显示.DS_Store文件

### ISSUE THREAD

**Issue by Leoan0131** [wisnuc/wisnuc-desktop-windows#47]
基本每一个目录下都有这个文件。不要显示。
![image](https://user-images.githubusercontent.com/24586770/30149237-75790272-93d9-11e7-99f1-18de08c5bf57.png)
![image](https://user-images.githubusercontent.com/24586770/30149244-7ae2b9ec-93d9-11e7-9d2f-79bbdfb77df1.png)

**Comment by Leoan0131** [comment]
不同平台有不同的隐藏文件类型。作为第三方平台，忠实反应上传内容是策略之一。另外一种策略是用户可以设置隐藏文件是否显示，明显这种需要的工作量大，而优先级与现有开发的计划任务相比较低。
短期内不做UE设计变更。

**Comment by juncaixinchi** [comment]
已忽略 .DS_Store
