### ISSUE TITLE
设备搜索问题 - process killed due to out of memory (identify too much)

### ISSUE THREAD

**Issue by trevorwang12** [wisnuc/wisnuc-desktop-windows#48]
用户在第一次登陆系统时候，PC客户端可以正常搜索到设备。

之后，系统发生如下问题：

![image](https://user-images.githubusercontent.com/20084315/30312941-2e46d67e-97ce-11e7-8cdf-4e20938fd212.png)

用户重装系统，重装后发现PC客户端，手机端再也无法搜索到设备，但用添加IP的方式可以正常登陆设备。

用户非多网段环境。

此问题1月份版本发布后，也有两位用户反馈出现同样问题，第一次能搜索到设备，重启设备后再也无法搜索到设备。

**Comment by Leoan0131** [comment]
merge with https://github.com/wisnuc/appifi/issues/388

**Comment by juncaixinchi** [comment]
服务器问题，已修复
