### ISSUE TITLE
设备存在，但局域网搜索未获取到设备dns，通过微信远程登陆，报错

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/wisnuc-desktop-windows#61]
![610377577446778418](https://user-images.githubusercontent.com/22342734/31653452-3930c61a-b355-11e7-91a4-7f23f852f8de.jpg)
![467502043666135599](https://user-images.githubusercontent.com/22342734/31653454-396b0c80-b355-11e7-954c-dd0d1443d802.jpg)

**Comment by juncaixinchi** [comment]
fixed in v1.2.3
