### ISSUE TITLE
任务传输中，重启设备，显示传输任务完成

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/wisnuc-desktop-windows#77]

**Comment by juncaixinchi** [comment]
fixed in v1.2.11

**Comment by kangxuwinsun** [comment]
![qq 20180104113750](https://user-images.githubusercontent.com/22342734/34549898-4fe44a64-f147-11e7-8950-86f9e0d97d17.png)


是重启页面显示传输完成提示语

**Comment by juncaixinchi** [comment]
fixed in v1.3.7
